import React from 'react'

const Home = () => {
  return (
    <div>
        <h1>Hello this is a home page</h1>
        io laudantium totam recusandae, libero consectetur iste facere corrupti eveniet eligendi. Iusto aliquam enim quos iure necessitatibus porro maxime error fugit temporibus, ipsa distinctio, quaerat ut minima soluta cupiditate voluptates modi nisi nam libero! Ex rerum dolor suscipit dolore eveniet ducimus magni explicabo qui. Aperiam, adipisci nesciunt perferendis ipsa voluptates accusamus dicta, consequuntur, tempore non necessitatibus laborum praesentium? Dolorem odit sed sit? Dolorem quos blanditiis animi necessitatibus, omnis veritatis totam, vel dolor sed reprehenderit et fugiat debitis officiis sint ducimus saepe velit quia quisquam perferendis nisi deleniti eveniet eius. Ipsum id magni quis illum, quibusdam labore nobis asperiores, numquam neque, dignissimos placeat. Voluptas, facere expedita delectus nihil omnis asperiores corrupti! Ratione fuga est repudiandae vero praesentium provident nulla delectus, sed ipsum possimus reiciendis doloremque quo eligendi ipsa saepe sapiente repellat nobis culpa minima consectetur porro facilis! Aspernatur accusantium fugiat laudantium et ratione fugit asperiores, dolore, inventore provident repellat, hic sit praesentium neque! Ipsam id atque earum esse voluptas voluptate alias quasi ullam, necessitatibus nemo deleniti provident dolores officiis veniam reprehenderit asperiores ad nobis omnis assumenda! Animi labore ipsa consequuntur aliquid, nam et laudantium itaque totam aliquam minima veniam obcaecati facere, corporis officia earum. Dolore incidunt commodi asperiores porro repellendus quaerat, rem similique eligendi dolorum id ipsa optio! Veritatis iste accusantium repellat iusto, numquam hic a atque laboriosam ea unde rem excepturi fugiat est saepe totam eaque exercitationem neque laborum dolorum officia deleniti necessitatibus! Animi magni ad voluptates dolorem minus ex dignissimos optio repudiandae, hic eum nulla voluptatem facilis nemo explicabo sint veniam dolorum dolor! Laboriosam eius ad aperiam consequuntur quod dicta suscipit praesentium ut omnis excepturi totam dignissimos repellat aut, veniam facere atque molestias eveniet, sapiente minus! Nostrum eaque voluptatum quos, ullam impedit esse, labore nam rerum nisi ducimus tenetur. Doloremque fuga sunt assumenda perspiciatis rerum aspernatur voluptatem id, sit animi expedita. Adipisci beatae pariatur consequatur reprehenderit delectus quod dolorem, suscipit perspiciatis id voluptas odit dolorum ad corporis optio nesciunt sapiente cum quisquam, nostrum minima nemo rem exercitationem nisi iure ducimus. Provident magnam deleniti vel? Esse veritatis vitae inventore natus quidem? Asperiores est odit expedita praesentium fuga aspernatur facere! Est ut iure expedita facere totam aperiam unde soluta dolor a pariatur, in, iusto iste rem accusamus veniam nesciunt quam recusandae nihil voluptate nulla eveniet eius! Officia, accusamus autem ratione atque tempora nemo omnis harum quasi deleniti eum.
      
    </div>
  )
}

export default Home
